### ISSUE TITLE
Allow non standard https port for monitoring

### ISSUE THREAD

**Issue by Schlurcher** [RaymiiOrg/certificate-expiry-monitor#11]
First and foremost thanks for this service!

I've got a site with a non-standard https port which I want to monitor for certificate expiration, which seems to currently not be possible unless I'm missing something. Am I?

If not it would be nice if your service would support this.

**Comment by Tntdruid** [comment]
I miss that, etc can't do cert check on cPanel server running on :2087

**Comment by DarissAK** [comment]
See my fork where I implemented this. Not terribly hard to do, just had to trace back all the functions that needed the arguments passed. My commit is more difficult to sort through since my IDE auto formatted everything if you're looking for my exact changes. I currently use this to monitor mumble certificates on random ports, works great for me thus far.
[https://github.com/DarissAK/certificate-expiry-monitor](https://github.com/DarissAK/certificate-expiry-monitor)

**Comment by RaymiiOrg** [comment]
IMHO, other ports and more advanced monitoring are not a job for this tool. Use something like Icinga, Nagios, zabbix etc,

**Comment by pnicolay** [comment]
This is not about monitoring but about certificate expiration testing... people don't realize that certificates are used on much more things like just HTTPS, also TELNET-SSL (which runs on port 992) uses them and can (could have been) tested with this tool.  It's a shame that people are so narrow minded with their humble opinions.
