### ISSUE TITLE
Can't read database: 3

### ISSUE THREAD

**Issue by mocten** [RaymiiOrg/certificate-expiry-monitor#33]
Received an error (Can't read database: 3) when submitting URL to be monitored

**Comment by sethtregenna** [comment]
+1

**Comment by HubertusDicke** [comment]
Hello,
is there a solution for Can't read database: 3 ?
kind regards

**Comment by RaymiiOrg** [comment]
should be working now.

**Comment by HubertusDicke** [comment]
Hello,

many thanks.

Yes, I was able to insert a new domain, but the confirmation email does 
not come in.

A test email to our adress was delivered: Email: certmon@accept-it.de.



Mit freundlichen Grüßen
i.A. Hubertus Dicke



Von:    "Remy" <notifications@github.com>
An:     "RaymiiOrg/certificate-expiry-monitor" 
<certificate-expiry-monitor@noreply.github.com>
Kopie:  "HubertusDicke" <hdicke@accept-it.de>, "Comment" 
<comment@noreply.github.com>
Datum:  04.05.2019 19:17
Betreff:        Re: [RaymiiOrg/certificate-expiry-monitor] Can't read 
database: 3 (#33)



should be working now.
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.


-----------------------------------------------------------------------------------------------------------------------------------
acceptIT GmbH
Klingenderstr. 22
33100 Paderborn
Deutschland

Tel. + 49 5251 693 98-0 | Fax -23
www.accept-it.de | www.travelXpense.de

Registergericht: Amtsgericht Paderborn, HRB 4154
Geschäftsführer: Stefan Lage
USt-Identifikationsnummer: DE813535846
-----------------------------------------------------------------------------------------------------------------------------------

**Comment by mocten** [comment]
Check your spam folder.

**Comment by HubertusDicke** [comment]
Hi,

nothing found in Spam or quarantine.

SMTP protocol: no entry for certmon@accept-it.de, only my testmail from 
private account.

Many thanks.

Mit freundlichen Grüßen
i.A. Hubertus Dicke



Von:    "mocten" <notifications@github.com>
An:     "RaymiiOrg/certificate-expiry-monitor" 
<certificate-expiry-monitor@noreply.github.com>
Kopie:  "HubertusDicke" <hdicke@accept-it.de>, "Comment" 
<comment@noreply.github.com>
Datum:  07.05.2019 15:04
Betreff:        Re: [RaymiiOrg/certificate-expiry-monitor] Can't read 
database: 3 (#33)



Check your spam folder. 

> On May 7, 2019, at 2:37 AM, HubertusDicke <notifications@github.com> 
wrote:
> 
> Hello, 
> 
> many thanks. 
> 
> Yes, I was able to insert a new domain, but the confirmation email does 
> not come in. 
> 
> A test email to our adress was delivered: Email: certmon@accept-it.de. 
> 
> 
> 
> Mit freundlichen Grüßen 
> i.A. Hubertus Dicke 
> 
> 
> 
> Von: "Remy" <notifications@github.com> 
> An: "RaymiiOrg/certificate-expiry-monitor" 
> <certificate-expiry-monitor@noreply.github.com> 
> Kopie: "HubertusDicke" <hdicke@accept-it.de>, "Comment" 
> <comment@noreply.github.com> 
> Datum: 04.05.2019 19:17 
> Betreff: Re: [RaymiiOrg/certificate-expiry-monitor] Can't read 
> database: 3 (#33) 
> 
> 
> 
> should be working now. 
> — 
> You are receiving this because you commented. 
> Reply to this email directly, view it on GitHub, or mute the thread. 
> 
> 
> 
----------------------------------------------------------------------------------------------------------------------------------- 

> acceptIT GmbH 
> Klingenderstr. 22 
> 33100 Paderborn 
> Deutschland 
> 
> Tel. + 49 5251 693 98-0 | Fax -23 
> www.accept-it.de | www.travelXpense.de 
> 
> Registergericht: Amtsgericht Paderborn, HRB 4154 
> Geschäftsführer: Stefan Lage 
> USt-Identifikationsnummer: DE813535846 
> 
-----------------------------------------------------------------------------------------------------------------------------------
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.


-----------------------------------------------------------------------------------------------------------------------------------
acceptIT GmbH
Klingenderstr. 22
33100 Paderborn
Deutschland

Tel. + 49 5251 693 98-0 | Fax -23
www.accept-it.de | www.travelXpense.de

Registergericht: Amtsgericht Paderborn, HRB 4154
Geschäftsführer: Stefan Lage
USt-Identifikationsnummer: DE813535846
-----------------------------------------------------------------------------------------------------------------------------------
